services:
  unofficial-api:
    image: 2noscript/unofficial-api:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - unofficial-api-data:/data
    restart: unless-stopped

volumes:
  unofficial-api-data:

